### PR TITLE
Common base

### PR DESCRIPTION
**Pull request by robertpainsi**
This is my first result of creating a common base :smiley_cat:. Most things have been done by scripts. I only had to do one thing by hand but checked the results for correctness automatically. The code won't be visitable on github.com, I guess, so you have to check it out. Here is a step by step explanation what I have done today.
- Determined which files are identical in _all_ themes, copied them to the MediterraneanCommon folder and created symbolic links in each theme.
- Added all common but slightly different files to the common folder and created symbolic links named *.css.common in each theme. Mostly from the Dark theme but it doesn't matter which theme I used. This has to be done because of this https://github.com/rbrito/pkg-mediterranean-gtk-themes/issues/19#issuecomment-72881579 Nothing fancy has been done yet.
- Removed all the selectors in the common files which differs to any other theme. So, e.g., I removed this code-block completely from the common gtk-widgets.css file even only the color property differs in all the themes.

```
.menuitem GtkCalendar,
.menuitem GtkCalendar.button,
.menuitem GtkCalendar.header,
.menuitem GtkCalendar.view {
/*    background-color: @menu_bg_color; */
    background-color: shade(@theme_bg_dark_color, 0.82);
    background-image: none;
    border-radius: 0px;
    border-style: solid;
    border-width: 0px;
    padding: 0px;

    color: @text_color;
}
```

This had to be done to benefit from the diff tool. We want to be sure that whole code blocks (selectors) are always used to automate all following processes. Further improvements can be done later. I checked it twice with meld. So if you would compare the common theme with all other ones, there is no added or modified line in the common theme but only added lines on each theme. So the common files only contains code which _all_ themes share.
- Now I created a backup of all css files. Always do backups! :smirk_cat:
- The content of each css file of each theme has been replaced with a single import to the corresponding symbolic link.
- Finally I just diff the backup css file with the common css file and added all diffs to the normal css file. ->

```
common file + own css file - import statement = backup file
```

So, every css in the themes imports the common css file which _all_ themes share but add the different code after the import state.

In the process I ignored following files: _gnome-apps.css, menu_frame.css, switch.css and unity-apps.css_ because they are only present in the MediterraneanTributeBlue theme. Also the gtk.css file has been ignored since it can't be merged at all atm.

### CODE REVIEW

**Comment by robertpainsi** [comment]
The appended script will check if the (common file + css file) - backup file = import statement

```
folders=(
"MediterraneanDark"
"MediterraneanDarkest"
"MediterraneanGrayDark"
"MediterraneanLight"
"MediterraneanLightDarkest"
"MediterraneanNight"
"MediterraneanNightDarkest"
"MediterraneanTribute"
"MediterraneanTributeBlue"
"MediterraneanTributeDark"
"MediterraneanWhite"
"MediterraneanWhiteNight"
)

for folder in "${folders[@]}"
do
  cd ~/.a/${folder}/gtk-3.0/
  pwd
# compare old version of css with new one including common base
  find . -type f -name "*.css" -and -not -name "gtk.css" -exec bash -c 'colordiff --ignore-blank-lines <(cat {}.old | sort) <(cat {} ../../MediterraneanCommon/gtk-3.0/{} | sort)' \;
done
```

Explanation:
- Find all theme css files except the gtk.css file
- Each found file will be concatenated with the corresponding common file, sorted and then compared with the backup/old file, also sorted. The result is the @import statement because this doesn't exist in the backup file.

**Comment by robertpainsi** [comment]
Closed it because it shouldn't be merged yet

**Comment by robertpainsi** [comment]
Just to clarify! I don't won't to replace files with links or other stuff. I like the folder/file structure the way it is now, like in the master. These commits are just the first steps to create a common base before we can even use a build system. The next steps would be (order may vary):
- Unify as much as possible by hand.
- Implement a build process which will do the converting, pre-processing, etc. Also generate the files and folder structure we have now.
- Convert the css files by using a better styling language (less, sass, stylus, whatever) to reduce the code as much as possible.

As far as I've seen, sass extends css. So we could use sass already in our build system without adapting any css files yet. I think this is awesome. After unifying (there are only a few steps left) and creating a build system, we can begin converting css to sass "rule by rule".

At then end we would have a common theme version (fixes will effect all themes), a build system (handles the pre/post-processing of the styling language and also the differences between themes) and a better styling language (shorter and easier handling of files).

So, what do you think guys?

**Comment by darvelo** [comment]
:+1: @robertpainsi I think this is spot on. The only thing I would add is:

It seems the GTK CSS has specific syntax (e.g. `@define-color calendar_text_color @theme_base_color;`) that Sass may not be able to compile into CSS. So the build system and conversion to sass probably have to be done together, otherwise we won't know if the build is working since it won't compile until all GTK-specific stuff is converted.

This may involve looking at [your earlier link](https://git.gnome.org/browse/gnome-themes-standard/commit/?id=c10689c7b2dc1352e7b329f58c9f653e5682dca5) to see how the GNOME devs did it. Some clever regex may be able to handle much if not all of it.

Also some of the spacing in the original code is really whacky. It would look better with a general rule of 4 spaces representing a tab character going forward, IMHO. Any decent text editor (vim, emacs, sublime, atom, etc.) can be configured to convert tabs to spaces.

I wish I could be in the trenches with you but I'm still looking for a job and can't devote as much time to this project as I would like to. :crying_cat_face: But I'll try to help where I can.

**Comment by robertpainsi** [comment]
Thanks for your feedback, I appreciate that!
Yes, I also think a clever regex will solve the problem with the defined colors.

Yesterday I found the github repo for the Numix theme which converted their code to sass too. They use some kind of functions to handle non css syntax stuff. See defined https://github.com/shimmerproject/Numix/blob/sass/gtk-3.0/scss/_functions.scss E.g. shade is a gtk property only, but by using a function it can be used like in the css file. So no need to adapt this code.

Also for the tab to space replacing I have a regex by hand. So this will be done asap. But it changes a lot. Especially all the xml files uses tabs... Atm I'm not sure which file extends should be included. '_.css' '_.xml' '_.rc' '_.txt' '_.md' '_.ini' I guess

No problem, good luck finding a job! :necktie:

**Comment by robertpainsi** [comment]
By converting the gtk variables to sass variables, do some reformatting (indentation, remove some unnecessary **and** faulty spaces), add a few functions to https://github.com/shimmerproject/Numix/blob/sass/gtk-3.0/scss/_functions.scss the sass converter works! Since everything can be done by regex, it's no work at all.

I did all these changes for the common/gtk-widgets.css (3000+ lines) already and at the end neither sass nor the gtk-widget-factory threw errors or doesn't look right. So, now I'm just waiting that https://github.com/rbrito/pkg-mediterranean-gtk-themes/pull/31 is inspected (and hopefully merged) and then beating some regexp out of my head to do all the necessary changes to get sass working. This will be just a work for an hour, I guess, but sass is always so picky with indentation. It doesn't allow tabs which is good ^^ and it also forces four spaces indentation. 5, 6 or 7 spaces aren't allowed

But stuff like:

```
border-color: alpha(black, 0.27)
              alpha(black, 0.13)
              alpha(black, 0.13)
              alpha(black, 0.13);
```

isn't allowed either. The indentation have to be 4, 8, 12, etc spaces not 4, 12. A little too much forcing in my opinion. But maybe there is just a flag somewhere to enable/disable this...

**Comment by darvelo** [comment]
@robertpainsi Nice find on the sass functions! Also, I believe you mean _indentation_. :wink: Thanks for the good luck too!

I think if you're able to get the sass conversions working, the "build system" can be a simple Makefile with a `sass` command inside, rather than using something more complex like the npm-based Gulp or Grunt I mentioned earlier. Then you could just use your existing Makefile (nice work) and depend on sass to compile with `@imports` rather than copying the common files with script.

**Comment by robertpainsi** [comment]
Ohh, there is one `sass --scss ...`
So no need to change the indentation at all except changing tabs to spaces. Cool!

**Comment by robertpainsi** [comment]
*indentation
...of course. That's why chrome always told me that it's misspelled ^^ (have to respell it everywhere -.-) Thanks for the hint! :smirk_cat:

@darvelo 
Yeah, that would be awesome. You are right, if we handle the import statements correctly, the makefile only needs the sass command. I guess this will be the last step for the current unifying process. After that the only (and most time consuming) process would be refactor all the sass/scss code to make it cleaner, shorter and therefore easier to manage. Also this may be the best time to get more people, especially sass and gtk developer, involved.

**Comment by robertpainsi** [comment]
Closed because of enhanced version. Details https://github.com/rbrito/pkg-mediterranean-gtk-themes/issues/19#issuecomment-73531040

**Pull request closed without merging**
